### ISSUE TITLE
use of unresolved identifier aknodeoutputplot (Xcode 9-Swift 4-V 4.0.1)

### ISSUE THREAD

**Issue by Tauf** [AudioKit/AudioKit#1076]
I have an app which uses EZAudioPlot and AKNodeOutputPlot. Everything was working fine but when updating to Xcode 9-Swift 4-V 4.0.1 (using CocoaPod installation), I get the compiler error: 

use of unresolved identifier aknodeoutputplot 

I'm not sure if it is because of this, but aknodeoutputplot uses EZAudioPlot in AudioKitUI-Swift.h, and the framework does not include/import the header EZAudioPlot.h, it has EZAudioPlotGL.h. 

Should I pod EZAudio for EZAudioPlot alongside with AudioKit, or does the AudioKit UI provide it? 
When I do not pod and import EZAudio, I also get the error: 

use of undeclared type EZAudioPlot 

Any help is appreciated. My supervisor is putting pressure on me to update the app for iOS 11. 

Thanks.

**Comment by megastep** [comment]
If you use CocoaPods, you now need to use `pod 'AudioKit/UI'` to get the AudioKitUI framework which implements these classes.

**Comment by andresinaka** [comment]
@Tauf I was having the same problem. If you are using CocoaPods you have to import `AudioKitUI` the same way you are importing `AudioKit`

```
import AudioKit
import AudioKitUI
```

**Comment by aure** [comment]
These answers should solve this for you, if not you can reopen the issue

**Comment by Tauf** [comment]
Thanks for the answers. I have removed EZAudio, and installed both 4.01 AK and AK UI. I cleaned and built it. Still having problem:

<img width="1678" alt="screen shot 2017-10-06 at 1 06 02 pm" src="https://user-images.githubusercontent.com/16407236/31296458-3a6a1f70-aa97-11e7-9d85-d9090268d1ea.png">

**Comment by MattTimmons** [comment]
I am having the same issue with Xcode 9.1 and iOS 11.1. 

I have both in my pod file:
pod 'AudioKit'
pod 'AudioKit/UI'

import AudioKit
import AudioKitUI

Module compiled with Swift 4.0 cannot be imported in Swift 4.0.1: ..../Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

**Comment by megastep** [comment]
Do you mean the Xcode beta? We only release binaries for the current stable release (currently 9.0.1). You'll have to compile them yourself and not use the pod in the meantime if you want to stick with that. Or frankly just use Xcode 9.0.1, the changes in 9.1 are really rather minor...
