### ISSUE TITLE
Recorder - corrupted waveform

### ISSUE THREAD

**Issue by Scitator** [AudioKit/AudioKit#1214]
Hello!

I have used AuditKit for several months, but recently found quite strange bug:
![audiokit_vs_dictaphone](https://user-images.githubusercontent.com/7606451/35283661-eb3a5478-0069-11e8-8244-62cc9a2fca23.png)
Here you can see audio spectrograms from AudioKit recorder (upper half) and typical iphone dictaphone (bottom one).

As you can see, Audiokit spectrograms have a lot of vertical noisy lines. There are a lot of artefacts and instability, if you work with sound like this one.

Let's look carefully at Audiokit file.
![image](https://user-images.githubusercontent.com/7606451/35284063-e9833f22-006a-11e8-9c7a-a7a703aa702b.png)
The cause of this line are these waveform anomaly peaks - small triangle in the center of upper graph.

Do anyone know how to solve this problem?
I tried a lot of different AKSetting configurations - but this bug is present everywhere.

Thank you!

**Comment by aure** [comment]
THe problem is not in the recorder I think , this looks like an oscillator bug that has been fixed.  What version of AudioKit are you using and what is your oscillator code?

**Comment by Scitator** [comment]
@aure 
So, my code below:
```
func setupMicrophone() {
        AKAudioFile.cleanTempDirectory()
        
        AKSettings.sampleRate = 44100

        AKSettings.audioInputEnabled = true
        AKSettings.bufferLength = .medium

        do {
            try AKSettings.setSession(category: .playAndRecord)
        } catch let error as NSError {
            let message = "Could not set session category. \(error), \(error.userInfo)"
            AKLog(message)
            ServerUtils.catchExceptionWithSentry(message)
        }
        AKSettings.defaultToSpeaker = true
        
        mic = AKMicrophone()
        micMixer = AKMixer(mic)
        recorder = try? AKNodeRecorder(node: micMixer)
        micBooster = AKBooster(micMixer)
        micBooster?.gain = 0
        
        mainMixer = AKMixer(micBooster)
        AudioKit.output = mainMixer
        
        inputPlot.node = mic
        
        AudioKit.start()
    }
```

**Comment by gaphex** [comment]
Can confirm that the bug is still present on the latest version of AudioKit (4.0.4).
Please find attached some screenshots
![screenshot 2018-01-24 14 31 26](https://user-images.githubusercontent.com/4992480/35330203-b199fb6a-0113-11e8-94c2-1265ba61b6dc.png)
![screenshot 2018-01-24 14 30 11](https://user-images.githubusercontent.com/4992480/35330204-b1ba0c84-0113-11e8-83c8-85d90bee03ae.png)

**Comment by dave234** [comment]
@Scitator Do you still get the distortion without ```inputPlot.node = mic```.

@gaphex Do you have a code sample as well?  It might help narrow down the issue.

**Comment by Scitator** [comment]
@dave234 
Yes, I have commented all lines with `inputPlot` and still had this issue.

@aure 
The bug is also reproducible in `develop` branch.

**Comment by Meekohi** [comment]
Just out of curiosity since it relates to my bug, which mic are you using for this (mobile device? lightning plug earpods?)

**Comment by Meekohi** [comment]
I have been doing some reading and my understanding is that most of the newer devices have mics that prefer a sampling rate of 48,000Hz instead of 41,100Hz. Also curious if you still see this behavior when switching to 48,000Hz (unfortunately doesn't help my case since we need to combine with some 41.1KHz data).

**Comment by gaphex** [comment]
@dave234 I was using the Recorder example from the repository, https://github.com/AudioKit/AudioKit/tree/master/Examples/iOS/Recorder
@Meekohi I was using an IPhone 6S for recording. Interestingly, the bug does not reproduce in the XCode simulator.

**Comment by Scitator** [comment]
@Meekohi 
I use Bottom microphone.
All tested KHz(16, 44.1, 48) have this bug.
All tested number of channels (1, 2) have this bug.

Interesting one: switching to AVSession - resolves this bug. So, looks like something in AudioKit goes wrong.

**Comment by aure** [comment]
@Scitator Can you explain what you mean by "switching to AVSession".  Do you mean AVAudioSession?  AVAudioSession is used in AudioKit as well, what setting of AVAudioSession solves this problem?

**Comment by aure** [comment]
Closing until more information (hopefully in the form of a project exhibiting the bug) is added.
