### ISSUE TITLE
AudioKit.midi.closeInput("Session 1") Not working

### ISSUE THREAD

**Issue by mekeo** [AudioKit/AudioKit#1462]
Hello! Working with Virtual MIDI ports, once I open the Session 1:

    AudioKit.midi.openInput("Session 1")

It's not possible to close, it doesn't work:

    AudioKit.midi.closeInput("Session 1")

Even AudioKit.midi.closeAllInputs()  doesn't seem to work.

After it, another  AudioKit.midi.openInput("Session 1") will result in duplicates MIDI In data.

Same with any other virtual inputs.

**Comment by aure** [comment]
Thi smight be fixed in develop.  I know its something that we worked on recently with Synth One. Getting duplicates is really strange though, I'm not sure how that's happening.

**Comment by aure** [comment]
I think this is fixed as of 4.5.1 or earlier, but if its not let me know.

**Comment by mekeo** [comment]
Hi Aure. Testing it with the last version and still doesn't work.
Something weird is happening ... 
If receivedMIDISetupChange() at init opens some MIDI inputs, can't be closed later, and opening again those input will duplicate
