### ISSUE TITLE
Xcode 12. Failed to build module AudioKit

### ISSUE THREAD

**Issue by impmaarten** [AudioKit/AudioKit#2134]
**AudioKit version**:
4.9.5, 4.10.1, and most likely more.

**Xcode version**:
12.0 beta (12A6159)

**Issue**:
Compiling with the AudioKit import results in the following highlighted issue.
`Failed to build module 'AudioKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.16.9 clang-1200.0.22.5)'`

It also results in "2660 issues" in the `x86_64-apple-ios-simulator.swiftinterface`, `arm64-apple-ios.swiftinterface` and most likely all generated swift interfaces for that matter.

**Work done**:
We have tested this in our app and in a newly created single-page app with only AudioKit imported via cocoa pods, both resulting in the same issue, described above.

I would love to know what will be done in order to solve this issue, since no apps using AudioKit, can be built on Xcode 12 Beta, thanks in advance.

**Comment by megastep** [comment]
Yeah it does sound like Xcode 12 doesn't like the compiled frameworks we provide for these releases. However I would suggest you try using the beta of AudioKit v5 which is shipped as XCFrameworks which have been working better.

Instructions here: https://github.com/AudioKit/Specs

v5.0.b1 is the version you want to be using.

**Comment by impmaarten** [comment]
We have updated the app to make use of **v5.0.b1** as you suggested @megastep, after some minor required changes we got it compilable (ex. AudoKit -> AKManager and required initialisers).

But we do run into some issues, for instance on iOS 14 Devices build from Xcode 11 and 12, we get the following issue when we assign `AKSampler` as output for the `AKManager.output` and start the `AKManager` with the following console crash details:

```
2020-07-06 13:35:18.590866+0200 X[45490:655818]  HALB_IOBufferManager_Client::GetIOBuffer: the stream index is out of range
2020-07-06 13:35:18.591072+0200 X[45490:655818]  HALB_IOBufferManager_Client::GetIOBuffer: the stream index is out of range
2020-07-06 13:35:18.602009+0200 X[45490:655818] [aqme] 255: AQDefaultDevice (1): output stream 0: null buffer
2020-07-06 13:35:18.602404+0200 X[45490:655818] [aqme] 1778: EXCEPTION thrown (-50): error != 0
2020-07-06 13:35:27.485964+0200 X[45490:655338] Initialize: Mach message timeout. Apparently deadlocked. Aborting now.
CoreSimulator 725.10 - Device: iPhone 11 Pro Max (X) - Runtime: iOS 14.0 (X) - DeviceType: iPhone 11 Pro Max
```

And on devices lower than iOS 14.0 the `AKSampler.stop` seems not to work at all.

I have tested it on a clean project and the output issue is present, so it doesn't seem implementation related.

Thanks in advance.

**Comment by quantamrhino** [comment]
+ 1 -- hitting the exact same thing.

**Comment by aure** [comment]
@impmaarten Please don't piggy back more issues onto previous issues. New issues are best addressed in fresh submissions.

**Comment by impmaarten** [comment]
> @impmaarten Please don't piggy back more issues onto previous issues. New issues are best addressed in fresh submissions.

Okay, I will create a new issue regarding the AKSampler in version 5, The reason for continuing on this issue, was that the suggested fix did not solve to the issue in my case.

**Comment by onsoku1230** [comment]
AudioKit frameworkを追加
(ただしModules内はx86_64のファイルのみ、影響はないと思っているが実機用のswiftmoduleも必要な場合はガッちゃんこする方法を教えて欲しいです、すみません)

結果、AudioKitではエラーは発生しない。
<img width="1065" alt="スクリーンショット 2021-01-14 23 44 04" src="https://user-images.githubusercontent.com/3013490/104605909-70243f80-56c2-11eb-9b40-da291a16d8fd.png">
