### ISSUE TITLE
AKAppleSequencer + AKMidiSampler do not work correctly on iOS 14 beta 6

### ISSUE THREAD

**Issue by TheHiddenDuck** [AudioKit/AudioKit#2238]
I record a simple midi sequence to the AKMusicTrack which is connected to the AKAppleSequencer with a loaded sound font. This has worked perfectly on all previous versions of iOS, but after updating to beta, I only hear the first note played.

This is how I initialize my sequencer:

```Swift
        sequencer = AKAppleSequencer()
        instrumentSampler = AKMIDISampler()
        
        let samplesPath = "...."
        do {
            try instrumentSampler!.loadEXS24(samplesPath)
            print("Loaded samples from: \(samplesPath)")
        } catch {
            print("Failed loading the samples file.")
        }
        
        instrumentTrack = sequencer!.newTrack()
        instrumentTrack?.setMIDIOutput(instrumentSampler!.midiIn)
        
        sequencer!.disableLooping()
```

After that I initialize and play the track:

```Swift
        if let track = instrumentTrack {
            let duration = AKDuration(beats: 3)
            track.add(noteNumber: MIDINoteNumber(48), velocity: 127, position: AKDuration(beats: 0), duration: AKDuration(beats: 1), channel: 0)
            track.add(noteNumber: MIDINoteNumber(49), velocity: 127, position: AKDuration(beats: 1), duration: AKDuration(beats: 1), channel: 0)
            track.add(noteNumber: MIDINoteNumber(50), velocity: 127, position: AKDuration(beats: 2), duration: AKDuration(beats: 1), channel: 0)
            
            sequencer.setLength(duration)
    
            sequencer.preroll()
        }
```

This would normally play three chromatic notes as expected. Now it only plays one. Also if I record several notes harmonically (as a chord) it would also only play one note.

I tried investigating my code but couldn't find anything. What could be the cause of this on iOS 14?

UPD:
Another observation - if i set duration to 0.99 instead of 1 - notes play as expected, so it looks like there is some issue when notes are supposed to overlap. This trick does not work if I want to play a chord and record several notes at the same position, even in different channels.

**Comment by aure** [comment]
These are pretty lightweight wrappers around Apple stuff so if you found a bug, might be better of reproducing outside of AK and filing a radar with Apple.

**Comment by aure** [comment]
I just tried your exact code on my recently iOS14-ified iPad and it works, maybe it is fixed?

**Comment by jdanthinne** [comment]
Still not fixed… Just tried on iOS14 official release, and got the same issue.
Setting duration to `AKDuration(beats: 0.99)` almost did the trick, but as I'm building a metronome, I'm setting `sequencer.enableLooping()`, and when the sequence has finished the first loop, the very first note (at position 0) is then never played…

**Comment by jdanthinne** [comment]
As expected, setting the position of first note at AKDuration(beats: 0.001) works 🥴

**Comment by TheHiddenDuck** [comment]
Hi @jdanthinne . I was able to workaround the issue by applying fix from this PR https://github.com/AudioKit/AudioKit/pull/2154 locally. I just copied source of AKMIDISampler to my project, applied this patch and using my custom sampler class instead of AKMIDISampler.

**Comment by jdanthinne** [comment]
@TheHiddenDuck Thanks, it works fine with the PR, but I had to do the same with `AKMIDIInstrument` as well, in `enableMIDI` method, in order to make `AKMIDICallbackInstrument` (for visual feedback) work.
