### ISSUE TITLE
com.apple.coreaudio.avfaudio - player did not see an IO cycle. 

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [AudioKit/AudioKit#2910]
### macOS Version(s) Used to Build

macOS 14.4.1 (23E224)

### Xcode Version(s)

Xcode 15

### Description

Hello,

In our Firebaze logs, we frequently encounter the error message "player did not see an IO cycle."
In our application, we have diligently followed the Apple guidelines outlined in the "Audio Guidelines for User-Controlled Playback and Recording Apps" document (https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioGuidelinesByAppType/AudioGuidelinesByAppType.html#//apple_ref/doc/uid/TP40007875-CH11-SW1).
To address this issue, we have implemented handling for the following states:
	•	AVAudioSession.interruptionNotification
	•	AVAudioSession.routeChangeNotification
	•	UIApplication.didEnterBackgroundNotification
	•	UIApplication.willEnterForegroundNotification
Additionally, we have referred to resources such as the following Stack Overflow thread for insights (https://stackoverflow.com/questions/74889075/avaudioplayernode-play-causes-crash-after-backgrounding-and-foregrounding-the).
We understand that upon route changes or transitions between background and foreground app states, it is necessary to rebuild our engine. Therefore, we have incorporated the method engine.rebuildGraph() to address these scenarios.
However, despite these measures, we continue to encounter the "player did not see an IO cycle" crash. Compounding the issue, we have only observed this crash in Firebase logs, and we have been unable to replicate it during our own testing.
Could you kindly provide some guidance or advice on resolving this issue?
Thank you.

![Screenshot](https://github.com/AudioKit/AudioKit/assets/3391456/5b11d7ca-f5d8-4509-98c0-7849a904978c)

### Crash Logs, Screenshots or Other Attachments (if applicable)

Fatal Exception: com.apple.coreaudio.avfaudio
0  CoreFoundation                 0x83f24 __exceptionPreprocess
1  libobjc.A.dylib                0x16018 objc_exception_throw
2  CoreFoundation                 0x18266c +[NSException raise:format:]
3  AVFAudio                       0x44cc AVAE_RaiseException(NSString*, ...)
4  AVFAudio                       0xf0120 AVAudioPlayerNodeImpl::StartImpl(AVAudioTime*)
5  AVFAudio                       0x493c AVAudioNodeImplBase::Start(AVAudioTime*)
6  AVFAudio                       0xec804 -[AVAudioPlayerNode play]
7  App                       0x84e324 AudioPlayer.play(from:to:at:completionCallbackType:completionHandler:) + 44 (AudioPlayer+Playback.swift:44)
8  App                       0x16836c AudioPlayer.playerPlay() + 558 (AudioPlayer.swift:558)
9  App                       0x123e54 partial apply for closure #1 in PlayerViewModel.play() + 185 (PlayerViewModel.swift:185)
10 App                       0x20baf0 thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>)
11 libdispatch.dylib              0x213c _dispatch_call_block_and_release
12 libdispatch.dylib              0x3dd4 _dispatch_client_callout
13 libdispatch.dylib              0x6f6c _dispatch_queue_override_invoke
14 libdispatch.dylib              0x15894 _dispatch_root_queue_drain
15 libdispatch.dylib              0x1609c _dispatch_worker_thread2
16 libsystem_pthread.dylib        0x48f8 _pthread_wqthread
17 libsystem_pthread.dylib        0x10cc start_wqthread

**Comment by jcavar** [comment]
I've ran into this as well. Here is a snippet that reproduces a problem which might help you understand if you are doing something similar:


```
let engine = AVAudioEngine()
let player = AVAudioPlayerNode()
engine.attach(player)
engine.connect(player, to: engine.mainMixerNode, format: nil)
let format = AVAudioFormat(standardFormatWithSampleRate: 44100, channels: 2)!
let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: 100)!
player.scheduleBuffer(buffer)
engine.mainMixerNode.auAudioUnit.inputBusses[0].isEnabled = false
try! engine.start()
player.play()
player.play(at: AVAudioTime(sampleTime: 0, atRate: 44100))
```

The root cause is that you are not allowed to start a player if it is in active audio chain.

**Comment by kunalzigma** [comment]
Hello, @Volodymyr-13 & @jcavar , am seeing same crashes. 
`
0x192112b28 __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x189fe6f78 objc_exception_throw + 60 (objc-exception.mm:356)
2   CoreFoundation                	0x192198234 +[NSException raise:format:arguments:] + 96 (NSException.m:0)
3   AVFAudio                      	0x1abafea84 AVAE_RaiseException(NSString*, ...) + 52 (AVAEInternal.h:69)
4   AVFAudio                      	0x1abbeb230 AVAudioPlayerNodeImpl::StartImpl(AVAudioTime*) + 2524 (AVAudioPlayerNode.mm:660)
5   AVFAudio                      	0x1abafeef4 AVAudioNodeImplBase::Start(AVAudioTime*) + 64 (AVAudioNodeImpl.h:176)
6   AVFAudio                      	0x1abbe7914 -[AVAudioPlayerNode play] + 68 (AVAudioPlayerNode.mm:1138)
7   AudioApp                          0x10285f534 AudioPlayer.play(from:to:at:completionCallbackType:) + 2444 (AudioPlayer+Playback.swift:43)
`
But don't know where am going wrong where am starting the player when it is in active audio chain. Like am seeing 0.2% sessions with this errors because of this. Cannot reproduce it. 
Is it possible that the code avoids starting the player when it is active audio chain? Like it does not do anything and not crash? Will be huge win for us as this is the only crash, we are seeing. Currently running app on AudioKit 5.6.4 using SPM.

**Comment by NickCulbertson** [comment]
I've noticed that you sometimes can't restart the engine immediately after route changes or interruptions. In those cases, I reload everything on a delay. I'm not rebuilding the graph like you, but maybe the solution of adding a delay will do the trick.  It might also be possible that the crash is occurring when the application is being exited entirely.

```
    func reloadAudio() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            if !conductor.engine.avEngine.isRunning {
                conductor.selectSound(conductor.currentSound)
                try? conductor.engine.start()
            }
        }
    }
```

**Comment by ilonashub** [comment]
We are also experiencing this crash from time to time. Were you able to find any solution or root cause for it?

**Comment by Volodymyr-13** [comment]
> We are also experiencing this crash from time to time. Were you able to find any solution or root cause for it?

Still no, some of the situations were fixed with help of NickCulbertson code bellow.,  but others not, looks like random: 

```
Fatal Exception: com.apple.coreaudio.avfaudio
0  CoreFoundation                 0xed5e0 __exceptionPreprocess
1  libobjc.A.dylib                0x2bc00 objc_exception_throw
2  CoreFoundation                 0x172334 +[NSException raise:format:]
3  AVFAudio                       0x2d20 AVAE_RaiseException(NSString*, ...)
4  AVFAudio                       0xdefc0 AVAudioPlayerNodeImpl::StartImpl(AVAudioTime*)
5  AVFAudio                       0x3190 AVAudioNodeImplBase::Start(AVAudioTime*)
6  AVFAudio                       0xdb6a4 -[AVAudioPlayerNode play]
7  Appnamehidden                       0x7ddd0 specialized AudioKitPlayer.play(from:to:at:completionCallbackType:completionHandler:) + 57 (AudioKitPlayer+Playback.swift:57)
8  Appnamehidden                       0x1d8614 AudioPlayer.playerPlay() + 598 (AudioPlayer.swift:598)
9  Appnamehidden                       0x1e3a04 specialized nAudioPlayer.playCommand(_:)
10 Appnamehidden                       0x1ddbf4 @objc AudioPlayer.playCommand(_:)
11 Appnamehidden                       0x1ddae0 thunk for @escaping @callee_guaranteed (@guaranteed MPRemoteCommandEvent) -> (@unowned MPRemoteCommandHandlerStatus) (<compiler-generated>)
12 MediaPlayer                    0x293e54 __40-[MPRemoteCommand addTargetWithHandler:]_block_invoke_2
13 MediaPlayer                    0x2936b0 __53-[MPRemoteCommand invokeCommandWithEvent:completion:]_block_invoke_2
14 CoreFoundation                 0x4540 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
15 CoreFoundation                 0x7c754 -[__NSFrozenDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
16 MediaPlayer                    0x29334c -[MPRemoteCommand invokeCommandWithEvent:completion:]
17 MediaPlayer                    0x24432c __57-[MPRemoteCommandCenter dispatchCommandEvent:completion:]_block_invoke
18 MediaPlayer                    0x243a48 -[MPRemoteCommandCenter _flushEventQueue]
19 MediaPlayer                    0x243e94 -[MPRemoteCommandCenter dispatchCommandEvent:completion:]
20 MediaPlayer                    0x244680 -[MPRemoteCommandCenter _pushMediaRemoteCommand:withOptions:completion:]
21 MediaPlayer                    0x242f40 __46-[MPRemoteCommandCenter _startMediaRemoteSync]_block_invoke
22 MediaRemote                    0x15b2a4 ___MRServiceClientRemoteResolvedPlayerPathCommandCallback_block_invoke.72
```

Some of them looks like related to state we added into debug: 

> handleRouteChange(_:): newDeviceAvailable
 CRASH after 

Or other case:

> handleRouteChange(_:): oldDeviceUnavailable
AVAudioSession interruptionNotification received
handleInterruption(_:) type = began
Player state: pause
 CRASH after

**Comment by Anywhere-Music-Player** [comment]
## Update: still happening in production, now with more Crashlytics evidence

Hi AudioKit team,

I previously opened this issue about:

`com.apple.coreaudio.avfaudio - player did not see an IO cycle`

We are still seeing this in production, and we now have more Crashlytics data plus user reports that make the failure pattern clearer.

### User-visible symptom

Users report that playback does not always crash immediately from their point of view. In many cases the app/player still appears to be running, the progress continues, queue/autoplay continues, but no audio is transmitted.

Examples from users:

- Local files saved on the phone, not iCloud.
- Happens with phone speaker, Bluetooth speaker, and CarPlay.
- After starting a playlist on shuffle, the first song plays, then at a random later track the player continues but no sound is heard.
- One user reports Bluetooth playback works for 2-3 songs, then the next song has no sound while the player still looks active.
- Force-closing the app sometimes temporarily helps, but the issue eventually returns.
- Reinstalling the app does not reliably fix it.

So from the user perspective this is not only "app crashed". It also looks like the audio graph/player state can get into a state where the UI and queue believe playback is active, but the output path is effectively silent or not rendering.

### Crashlytics data

Recent production window checked: `2026-06-14` to `2026-06-21`.

We found multiple fatal Crashlytics groups with the same underlying exception:

`com.apple.coreaudio.avfaudio - player did not see an IO cycle.`

### Issue 1

`[Anywhere] AudioKitPlayer+Playback.swift - AudioKitPlayer.play(completionHandler:)`

- Crashlytics issue id: `fe26bfacfe88a92babedbd92a3787d71`
- Events: `6`
- Impacted users: `3`
- First seen version: `0.9.104`
- Last seen version: `2026.6.0`
- Signal: regressed
- Top version in this time window: `2026.6.0 (13)` with 5 events
- OS:
  - `iOS 26.5.0`: 5 events
  - `iOS 17.5.1`: 1 event
- Devices:
  - iPhone 11 Pro
  - iPhone 15
  - iPhone SE 3rd generation

Sample stack:

```text
Fatal Exception: com.apple.coreaudio.avfaudio
player did not see an IO cycle.

at AVAudioPlayerNodeImpl::StartImpl(AVAudioTime*)
at AVAudioNodeImplBase::Start(AVAudioTime*)
at -[AVAudioPlayerNode play]
at AudioKitPlayer.play(completionHandler:)
at AnywhereAudioPlayer.playerPlay(...)
at AnywhereAudioPlayer.remoteStartPlaybackIfNeeded()
at AnywhereAudioPlayer.playCommand(_:)
at MPRemoteCommandCenter dispatch
```

This one happened from a remote play command path.

### Issue 2

`[Anywhere] AudioKitPlayer+Playback.swift - AudioKitPlayer.seek(time:completionHandler:)`

- Crashlytics issue id: `ff0ef9200fb9ec74bac71e5da8ca035e`
- Events: `2`
- Impacted users: `2`
- First seen version: `0.9.73`
- Last seen version: `2026.6.0`
- Signal: regressed

Sample context:

- Process state: `BACKGROUND`
- CarPlay connected: `true`
- Visible CarPlay template: `CPNowPlayingTemplate`
- Route change notification counter: `14`
- Interruption notification counter: `3`
- App version: `2026.6.0 (13)`
- Device: iPhone 17
- OS: iOS 26.3.0

Sample stack:

```text
Fatal Exception: com.apple.coreaudio.avfaudio
player did not see an IO cycle.

at AVAudioPlayerNodeImpl::StartImpl(AVAudioTime*)
at AVAudioNodeImplBase::Start(AVAudioTime*)
at -[AVAudioPlayerNode play]
at AudioKitPlayer.seek(time:completionHandler:)
at AnywhereAudioPlayer.seek(to:forRemote:)
at AnywhereAudioPlayer.changePlaybackPosition(_:)
at MPRemoteCommandCenter dispatch
```

Important breadcrumbs before the crash:

```text
UIApplication didEnterBackgroundNotification

Audio playerPlay request |
route=Speaker
state=starting
engineRunning=false
playerEngineNil=true

Audio graph attach start
Audio graph attach complete |
engineRunning=false
playerEngineNil=false

Seek Error: com.apple.coreaudio.avfaudio error 561015905

Audio playerPlay request |
engineRunning=false
playerEngineNil=false

Seek Error: com.apple.coreaudio.avfaudio error 561015905

UIApplication willEnterForegroundNotification
Player playing: Maroon 5 - Sugar

UIApplication didEnterBackgroundNotification
UIApplication willEnterForegroundNotification
UIApplication didEnterBackgroundNotification
```

This suggests we can reach `AVAudioPlayerNode.play()` from a remote seek / background / CarPlay path while the engine is attached but has not produced a valid IO render cycle.

### Issue 3

`[Anywhere] AudioKitPlayer+Playback.swift - AudioKitPlayer.play(from:completionHandler:)`

- Crashlytics issue id: `ced22910decc4a86a4164ee403abb777`
- Events: `1`
- Impacted users: `1`
- First seen version: `0.9.120`
- Last seen version: `2026.6.0`

Sample context included interruption and CarPlay route changes.

Breadcrumbs:

```text
AVAudioSession interruptionNotification received
handleInterruption type = began
Player pause

AVAudioSession routeChangeNotification received
routeConfigurationChange

handleInterruption type = ended
handleInterruption type = ended with shouldResume

Player stop and reset
Audio graph attach start |
route=CarAudio:CarPlay
state=rebuilding
engineRunning=false
playerEngineNil=true

Audio graph attach complete |
route=CarAudio:CarPlay
state=rebuilding
engineRunning=false
playerEngineNil=false

Audio playerPlay request |
route=CarAudio:CarPlay
state=starting
engineRunning=false
playerEngineNil=false

Player stop and reset
Audio graph attach start
Audio graph attach complete
Player playing
```

Stack:

```text
Fatal Exception: com.apple.coreaudio.avfaudio
player did not see an IO cycle.

at AVAudioPlayerNodeImpl::StartImpl(AVAudioTime*)
at AVAudioNodeImplBase::Start(AVAudioTime*)
at -[AVAudioPlayerNode play]
at AudioKitPlayer.play(from:completionHandler:)
at AnywhereAudioPlayer.playerPlay(...)
at AnywhereAudioPlayer.seek(...)
at MPRemoteCommandCenter dispatch
```

### Related graph rebuild crash

We also saw a separate fatal issue during graph rebuild/setup:

`com.apple.coreaudio.avfaudio - required condition is false: [_nodes containsObject: node]`

Crashlytics issue id:

`db143b08e5deadce56dbe865c36bc393`

This appears to happen when disconnecting/detaching nodes that are not actually attached to the current `AVAudioEngine`. We are fixing our side by making graph teardown idempotent and checking `node.engine` before `disconnectNodeOutput` / `detach`.

### Current architecture

We are using an AudioKit-based player with:

- `AVAudioEngine`
- two `AVAudioPlayerNode`-backed AudioKit players for crossfade / dry-wet switching
- mixer / EQ / time-pitch graph
- handling for:
  - `AVAudioSession.interruptionNotification`
  - `AVAudioSession.routeChangeNotification`
  - `UIApplication.didEnterBackgroundNotification`
  - `UIApplication.willEnterForegroundNotification`
  - MPRemoteCommandCenter play / pause / seek / next / previous
  - CarPlay now playing and template navigation

When route/interruption/background events happen, we rebuild or reconnect the graph and then resume if playback was active.

### What we changed on our side

We are currently testing a defensive patch with these changes:

1. Serialize playback commands through a single command lane so route changes, interruption resume, remote seek, next-track completion, and user taps do not mutate the graph concurrently.

2. Make graph teardown idempotent:
   - only disconnect/detach a node if `node.engine != nil`
   - use the actual attached engine from `node.engine`
   - avoid assuming all nodes are attached to the current `AVAudioEngine`

3. Do not deactivate the audio session on background if our high-level playback state still says playback should continue.

4. Before calling `AVAudioPlayerNode.play()`, check that:
   - the player node is attached to a running engine
   - `playerNode.lastRenderTime != nil`

5. If the engine has just started but `lastRenderTime` is still nil, delay playback very briefly and retry through the serialized playback command lane.

In other words, we are treating "engine is running" as not strong enough. We are now also waiting until the player node has observed at least one render/IO cycle before calling `play()`.

### Question

Does this match the expected failure mode of `AVAudioPlayerNode.play()`?

Specifically:

1. Is `engine.isRunning == true` insufficient as a readiness check before `AVAudioPlayerNode.play()` after route changes, interruption resume, background/foreground transitions, Bluetooth changes, or CarPlay remote commands?

2. Is `playerNode.lastRenderTime != nil` a reasonable guard to indicate that the node/engine has observed an IO cycle and that calling `play()` is safer?

3. Is there a better AudioKit-level API or recommended pattern for this state?
   For example:
   - a callback when AudioKit/AVAudioEngine has completed the first render cycle after `engine.start()`
   - a safe delayed start helper
   - a graph rebuild helper that avoids starting player nodes before the output path is stable

4. Does AudioKit have any internal expectation that `Player.play()` can be called immediately after `engine.start()` / graph rebuild, or should apps always defer until the engine has rendered?

5. Are there known issues around Bluetooth / CarPlay / remote commands where `AVAudioPlayerNode.play()` can throw this exception even after `engine.start()` succeeds?

### Why I suspect this is timing-related

The Crashlytics breadcrumbs repeatedly show this pattern:

```text
graph attach complete
engineRunning=false
playerEngineNil=false
playerPlay request
engineRunning=false or just started
AVAudioPlayerNode.play()
Fatal: player did not see an IO cycle
```

The fatal crash happens inside `-[AVAudioPlayerNode play]`, not while scheduling the file.

We also see it from remote command paths and background/CarPlay paths, not only from normal foreground button taps.

The most likely sequence seems to be:

1. Route/interruption/background/CarPlay event occurs.
2. App rebuilds or reconnects graph.
3. App starts engine.
4. App immediately calls player node `play()`.
5. AVFAudio has not produced an IO cycle yet.
6. `AVAudioPlayerNode.play()` raises `player did not see an IO cycle`.

### What would help

Any guidance on the correct AudioKit/AVAudioEngine readiness boundary would be very helpful.

If the maintainers think this is outside AudioKit and purely an AVFAudio timing rule, that is also useful to know. But if AudioKit's `Player.play()` or similar APIs can protect against this internally, it may prevent crashes for other apps too.

Thanks.

@aure @NickCulbertson
