### ISSUE TITLE
Unreliable currentTime

### ISSUE THREAD

**Issue by andreamazz** [audiokit/AudioKit#458]
Hi all.
I'm currently using AudioKit to play a file and show its waveform. It's working great so far. I'm having issues showing the current progress on the waveform though.  
I'm using `CADisplayLink` to update and move a simple 1px wide view (a cursor) over the waveform, like this:
<img width="437" alt="screen shot 2016-07-07 at 12 19 08" src="https://cloud.githubusercontent.com/assets/570797/16650182/17d3fc9a-443d-11e6-83fe-9e43381227a5.png">

I noticed that the value of currentTime is unreliable in two ways:
- `currentTime` tends to "lag" behind: at the start of the song the waveform under the cursor matches the song, but as time passes, the sound and the visual cue don't match anymore. In fact when the song ends, the `currentTime` value is still a couple of seconds (or more) behind. So if a 40 seconds audio is played, once the song is over, currentTime is still around the 37 seconds mark.
- when the player is paused, `currentTime` defaults to either 0 or to the latest value passed in `playFrom(_:)`. I think it would be better to always have the last known state of the song, so if the player is paused e.g. at the 30s, `currentTime` should reflect that value instead of 0.

For point 1 I'm not sure if it's an issue with my implementation, do you think that using `CADisplayLink` is the best approach?

```swift
  displayLink = CADisplayLink(target: self, selector: #selector(PlayerViewController.update))
  displayLink?.addToRunLoop(NSRunLoop.mainRunLoop(), forMode: NSDefaultRunLoopMode)

  // ...

  func update() {
    if let player = player, song = song where song.duration > 0 {
      let progress = Globals.WaveWidth * ((player.currentTime ?? 0) / song.duration)
      progressView.frame = CGRect(x: progress, y: 0.0, width: 2.0, height: Double(plotScroll?.frame.height ?? 0))
    }
  }
```

Thanks

**Comment by andreamazz** [comment]
As a followup it's also worth noting that trying to `playFrom(:_)` a location near the end of the song, results in a crash:
```swift
player.playFrom(song.duration * 0.95)
```

**Comment by laurentVeliscek** [comment]
Hi Andreas,

The bug you describe should have been fixed in the develop branch version of akaudioplayer. 

Playing is much more reliable, and playhead won't be zero anymore when pausing.


There's an audio player playground in develop with a "moving slider" that reflects player playhead. I noticed too that it seemed to be some late. It may be because of long buffer length setting. 
We're working on lowering the buffer's length so it should help to increase accuracy of playhead' value.

Please let us know if you still get buggy behavior with this version of akaudioplayer...

Laurent.

Envoyé de mon iPhone

> Le 7 juil. 2016 à 12:21, Andrea Mazzini <notifications@github.com> a écrit :
> 
> Hi all.
> I'm currently using AudioKit to play a file and show its waveform. It's working great so far. I'm having issues showing the current progress on the waveform though.
> 
> I'm using CADisplayLink to update and move a simple 1px wide view (a cursor) over the waveform, like this:
> 
> 
> I noticed that the value of currentTime is unreliable in two ways:
> 
> currentTime tends to "lag" behind: at the start of the song the waveform under the cursor matches the song, but as time passes, the sound and the visual cue don't match anymore. In fact when the song ends, the currentTime value is still a couple of seconds (or more) behind. So if a 40 seconds audio is played, once the song is over, currentTime is still around the 37 seconds mark.
> when the player is paused, currentTime defaults to either 0 or to the latest value passed in playFrom(_:). I think it would be better to always have the last known state of the song, so if the player is paused e.g. at the 30s, currentTime should reflect that value instead of 0.
> For point 1 I'm not sure if it's an issue with my implementation, do you think that using CADisplayLink is the best approach?
> 
> displayLink = CADisplayLink(target: self, selector: #selector(PlayerViewController.update)) displayLink?.addToRunLoop(NSRunLoop.mainRunLoop(), forMode: NSDefaultRunLoopMode) // ... func update() { if let player = player, song = song where song.duration > 0 { let progress = Globals.WaveWidth * ((player.currentTime ?? 0) / song.duration) progressView.frame = CGRect(x: progress, y: 0.0, width: 2.0, height: Double(plotScroll?.frame.height ?? 0)) } }
> Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Envoyé de mon iPhone

**Comment by aure** [comment]
I believe this is indeed fixed in develop.

**Comment by andreamazz** [comment]
Hi @aure 
I just tested on the `develop` branch, and the issue persists. Now i get this warning on the console: 
```
AKAudioPlayer cannot set a startTime bigger that endTime: 37.6424489795918 seconds
```
so that fixes the possible crash, but the cursor is still lagging behind in the waveform.

**Comment by andreamazz** [comment]
I'm currently testing this with a file with a duration of 40 seconds. I noticed that once the file is loaded, the player returns an endTime of 37,6 seconds. If I understand this correctly, it should match the duration of the song, right? I'm wondering if this issue is related to the sample rate of the file. What do you think?

**Comment by laurentVeliscek** [comment]
The answer is in the question... Did you check your files sample rate ?

Laurent.

Envoyé de mon iPhone

**Comment by andreamazz** [comment]
Yeah, the sample rate of the file is 44100 Hz. I just checked and it's actually rendered as 44100.0 in AudioKit, so that's not the issue.
I can circumvent this issue by using the player's `endTime` as reference, and apply a scaling to render the correct time for the user, but I'm still puzzled by this 😃

**Comment by aure** [comment]
Do you want to send us a link to the file or email it to me at aure at audiokit.io?

**Comment by andreamazz** [comment]
Hi @aure, thanks for the help. After some digging I found the culprit. 
I'm importing files from the media library, and I double and triple checked the importer a while ago, only to find out now that it's calculating the wrong file duration.
What tricked me is that the Apple Music app reports the same duration, but it's wrong.
So in the end I just need to discard that value and trust the `endTime` of AKAudioPlayer.

Thanks again for the support and the amazing library.
