### ISSUE TITLE
AudioKit submitted to iTC fails validation on CFBundleSupportedPlatforms in Info.plist

### ISSUE THREAD

**Issue by larsacus** [audiokit/AudioKit#567]
When submitting an application that includes AudioKit via Carthage to iTunesConnect, the build as it is built from Carthage will fail validation with the error:

> We have discovered one or more issues with your recent delivery for <app name>. To process your delivery, the following issues must be corrected:
> 
> **Invalid Bundle** - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

I don't think this is an Xcode 8 related thing since the actual validation fails on the iTunesConnect side, which implies this is a new requirement that has been added recently: https://forums.developer.apple.com/thread/62261

Manually removing or scripting the removal of the `CFBundleSupportedPlatforms` key altogether from `AudioKit.framework/Info.plist` allows passing submission. It appears simply changing the value from `iPhoneSimulator` to `iPhoneOS` will also work per the linked thread.

**Comment by megastep** [comment]
Yes, we actually have a workaround in the fix-frameworks.sh script on the devel branch. The next release of AudioKit should fix this more broadly.

**Comment by iSpartak** [comment]
just wonder when?  it also doesn't work for ad-hoc

**Comment by larsacus** [comment]
I'm curious to know why out of all of my dependencies (built with Carthage) in my project, why this one is the only one that needs a fix-frameworks script? Is it even necessary? Everyone else seems to be configured properly without one.

**Comment by iSpartak** [comment]
I just downloaded level branch and build framework for iOS via ./build_frameworks.sh   The issue is still there. Or I suppose to execute fix-frameworks.sh as well? On which particulary step?

**Comment by larsacus** [comment]
@iSpartak Follow the instructions in [install.md](https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md) for using `fix-frameworks.sh`. However, if you are building on Xcode 8, you may run into the same issue I ran into in #570 with that script un-signing your framework before submission.

**Comment by megastep** [comment]
The issue was because the App Store would reject frameworks that included simulator binary slices, so we had to strip them out so that people could submit it. If this is no longer a requirement, then you could just try skipping the script.

`fix-frameworks.sh` is supposed to be called as part of your own build process (in one of the run phases), whereas `build_frameworks.sh` is the command used to put together the universal frameworks. You typically only run that one once. However I'm thinking we'll probably move the fix for the plist issue into this script since it can be done there.

**Comment by iSpartak** [comment]
Thanks guys.  @megastep when do you plan to have a fix in production version?

**Comment by megastep** [comment]
I'm probably gonna do that real soon (if not right now). We need to push out a new version with fixed binary frameworks anyway. Trying to get a bit more clarity on the Carthage issue though.

**Comment by megastep** [comment]
I have just committed a fix to the `build_frameworks.sh` script that should build correct frameworks now (on the `devel` branch). This is no longer fixed by the `fix-framework.sh` script so let me know how this works for you with or without using this script.

Hopefully this fixes the issues and we can release a new version soon.

**Comment by iSpartak** [comment]
Just build from dev and added AudioKit.framework to my project but still have a problem. The issue with CFBundleSupportedPlatforms seems to be gone but now I am getting 

code = 0;
            description = "Failed to verify bitcode in AudioKit.framework/AudioKit:\nerror: Cannot extract bundle from /var/folders/ys/jb204tcx2k54gs7w0czgwn_00000gn/T/XcodeDistPipeline.mMy/Root/Payload/LS Tools.app/Frameworks/AudioKit.framework/AudioKit (i386)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }
    );

**Comment by megastep** [comment]
Well that is interesting, and considering it is singling out an i386 slice I wonder if using the fix-frameworks.sh script might help here?

**Comment by megastep** [comment]
Also, we explicitly don't build Bitcode for simulator slices, mostly to save some disk space since it's not a requirement and these slices won't be used for device builds anyway. You could try to enable it and see if it helps by changing `ENABLE_BITCODE = NO` to YES in `simulator.xcconfig`, then rebuild the framework.

**Comment by larsacus** [comment]
@megastep I don't use the `build_frameworks.sh` script. My dependencies are managed together using Carthage's cartfile and built using `carthage build --platform iOS`

**Comment by iSpartak** [comment]
thanks @megastep, unfortunately it did not help - the same error :(   Worth to mention I am using Objective C not Swift. But I do not think this is the issue. Everything is working perfectly in Simulator but failed when I am building Ad-Hoc :(

**Comment by megastep** [comment]
@iSpartak I don't think this is a language issue, rather the error is about verifying Bitcode. Another possibility is that i386 slice - it might just be completely obsolete now, we should try building with just x86_64 since I don't think 32-bit devices are even supported by iOS 9.

**Comment by larsacus** [comment]
@megastep For just iPhones, the 4S, 5, 5C are all supported under iOS 9 and are 32-bit devices. Even iOS 10 supports 5 and 5C.

**Comment by megastep** [comment]
That is true, and we do build armv7 slices for devices. However I think i386 has been obsoleted in the simulator builds for a good long while...

**Comment by megastep** [comment]
@iSpartak I just committed a possible fix to the simulator configuration, please pull from the `devel` branch, rebuild the framework and let me know if it helps with submission.

**Comment by iSpartak** [comment]
@megastep no luck ;(

code = 0;
            description = "Failed to verify bitcode in AudioKit.framework/AudioKit:\nerror: Cannot extract bundle from /var/folders/ys/jb204tcx2k54gs7w0czgwn_00000gn/T/XcodeDistPipeline.R9y/Root/Payload/LS Tools.app/Frameworks/AudioKit.framework/AudioKit (x86_64)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }
    );
}

**Comment by megastep** [comment]
@iSpartak then we might be stuck with using the fix-framework.sh script to strip the simulator slices I'm afraid.

**Comment by iSpartak** [comment]
@megastep new 3.4.2 still have the same issue if complile bitcode is on :(   

description = "Failed to verify bitcode in AudioKit.framework/AudioKit:\nerror: Cannot extract bundle from /var/folders/ys/jb204tcx2k54gs7w0czgwn_00000gn/T/XcodeDistPipeline.zlk/Root/Payload/LS Tools.app/Frameworks/AudioKit.framework/AudioKit (i386)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }
    );
}

**Comment by megastep** [comment]
@iSpartak yeah you do need to run the fix-framework.sh script in your run phase, as the App Store will reject binaries with simulator slices in them.

**Comment by iSpartak** [comment]
@megastep sorry, I am not sure I understand. I am talking about release version from http://audiokit.io/downloads/

"The AudioKit-*.zip archives contain universal precompiled frameworks for each platform, ready to drag and drop in your own projects"

I just drag& drop framework as per instruction. This doesn't work if I try to submit my app for ad-hoc or App Store. Can this page somehow be updated with correct instruction how to use this brilliant lib (really!) in production.

**Comment by megastep** [comment]
@iSpartak Sorry if this page doesn't explicitly mention it, but the following file linked to it does mention what to do: https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md

@aure we should probably have something about the handling of Bitcode by the script on the downloads page.

**Comment by aure** [comment]
What's the status of this issue?

**Comment by aure** [comment]
Closing this issue until further information, feel free to reopen.
