### ISSUE TITLE
Crash (exception) on Audiokit.start() since updating from 3.5 to 3.6 

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [audiokit/AudioKit#857]
Swift 3.1
iPhone7
Audiokit 3.6 (cocoa pod)

I get this printed on the console.. 
54:   ERROR:    [0x1a6f58c40] >avae> AVAudioEngineGraph.mm:2515: PerformCommand: error -10875 (OSCode = kAudioUnitErr_FailedInitialization)

its when Audiokit.start() is called, which throws an exception internally.

Everything was working fine until I updated Xcode to 8.3.2 and then updated to 3.6 audiokit

I´ve tried all combinations of setting the audio category, setting background audio modes and enabling inter-app audio!

It works fine on the sim???!!!!

**Comment by aure** [comment]
A little code would help have some idea what could be going wrong.

**Comment by LeeMatthewHiggins** [comment]
Its quite a lot of code. Just been commenting out until it works, seems that when I remove my FFT stage its working again. so it looks like 
mic.avAudioNode.installTap(onBus: 0,
                                     bufferSize: 512,
                                     format: AudioKit.format) { [weak self] (buffer, _) -> Void in.......
is the root of the issue....
Was working fine...

**Comment by aure** [comment]
I can't think of any particular change that would have made that happen, but you can pull up the git history of the FFT or any file and show me what I screwed up.  It could also be Apple, but most likely me.

**Comment by LeeMatthewHiggins** [comment]
It seems installing taps is broken! I was installing on a node after the mic (a AKHighPassFilter) if I do that to crashes. if I install directly to the mic, the tap callback(block) is never called.. :(

**Comment by aure** [comment]
You can also attach nodes to mixers safely.  So, you can do mixer  = AKMixer(highPassFilteredsignal) and then tap that and it should be fine.

**Comment by LeeMatthewHiggins** [comment]
I will try this tomorrow

**Comment by LeeMatthewHiggins** [comment]
I´m finding quite a few changes in the framework behaviour on 3.6. An output must now be set  (Audiokit.output = ). In 3.5 I was just plotting a FFT of the mic without setting Audiokit.output and it worked. now it has to be set else no callbacks are invoked.

**Comment by aure** [comment]
AudioKit output needs to be connected to the mic for the mic to generate data.  I'm pretty sure that was always the case since AudioKit nodes rely on a pull model.  I'd love to see the code that worked before but doesn't now.  In any case, what action can I do to address this issue?

**Comment by lususvir** [comment]
I am also getting an exception error. I changed nothing in my code except upgrading from 3.5 to 3.6. 

54: ERROR: >avae> AVAudioEngineGraph.mm:2515: PerformCommand: error -10851

My setup code:

     AKSettings.bufferLength = .medium
        
        do {
            try AKSettings.setSession(category: .playAndRecord, with: .defaultToSpeaker)
        } catch {
            print("Errored setting category.")
        }
        AKAudioFile.cleanTempDirectory()
        
        // Session settings
        AKSettings.bufferLength = .medium
        AKSettings.defaultToSpeaker = true
        
        // Patching
        let mic = AKMicrophone()
        let micMixer = AKMixer(mic)
        micBooster = AKBooster(micMixer)
        
        // Will set the level of microphone monitoring
        micBooster!.gain = 0
        recorder = try? AKNodeRecorder(node: micMixer)
        player = try? AKAudioPlayer(file: (recorder?.audioFile)!)
        player?.looping = false
        player?.completionHandler = playingEnded
        
        moogLadder = AKMoogLadder(player!)
        
        let mainMixer = AKMixer(moogLadder!, micBooster!)
        
        AudioKit.output = mainMixer
        AudioKit.start()

All I'm trying to do in my app is record audio. No effects or audio processing of any kind. It's basically a voice memos type app.

**Comment by lususvir** [comment]
Actually, here is the entire output if it helps:

    54: ERROR: >DDAgg> DefaultDeviceAggregate.cpp:724: BuildAggregate: Error finding valid input or output devices!
    318: error -66680 finding/initializing AQDefaultDevice
    892: failed: -10851 (enable 1, outf< 2 ch,      0 Hz, Int16, inter> inf< 2 ch,      0 Hz, Int16, inter>)
    318: error -66680 finding/initializing AQDefaultDevice
    108: * * * NULL AQIONode object
    771: Can't make UISound Renderer
    initialize() AKAudioPlayer Warning:  "976E8C71-7E07-43B1-866A-DD4364362E56.caf" is an empty file
    318: error -66680 finding/initializing AQDefaultDevice
    318: error -66680 finding/initializing AQDefaultDevice
    892: failed: -10851 (enable 3, outf< 2 ch,      0 Hz, Int16, inter> inf< 2 ch,      0 Hz, Int16, inter>)
    318: error -66680 finding/initializing AQDefaultDevice
    318: error -66680 finding/initializing AQDefaultDevice
    892: failed: -10851 (enable 3, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Int16, inter>)
    54:   ERROR:    >avae> AVAudioEngineGraph.mm:2515: PerformCommand: error -10851
     *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10851'
    *** First throw call stack:
    (
	0   CoreFoundation                      0x0000000114aa8b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011410e141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000114aaccf2 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x0000000115f9ca9e _Z19AVAE_RaiseExceptionP8NSStringz + 158
	4   AVFAudio                            0x0000000115f41cf0 _ZNK18AVAudioEngineGraph14PerformCommandER11AUGraphNodeNS_12ENodeCommandEPvj + 1764
	5   AVFAudio                            0x0000000115f42a42 _ZN18AVAudioEngineGraph10InitializeEv + 524
	6   AVFAudio                            0x0000000115fa5145 _ZN17AVAudioEngineImpl10InitializeEv + 29
	7   AVFAudio                            0x0000000115fa45a4 -[AVAudioEngine prepare] + 58
	8   AudioKit                            0x0000000113a24e63 _TZFC8AudioKit8AudioKit5startfT_T_ + 371
	9   Audiomesh                           0x000000010debebfc _TFC9Audiomesh13RecorderModal11viewDidLoadfT_T_ + 3052
	10  Audiomesh                           0x000000010debefb2 _TToFC9Audiomesh13RecorderModal11viewDidLoadfT_T_ + 34
	11  UIKit                               0x0000000111bb3cca -[UIViewController loadViewIfRequired] + 1235
	12  UIKit                               0x0000000111bb410a -[UIViewController view] + 27
	13  UIKit                               0x0000000111c005eb -[UINavigationController preferredContentSize] + 197
	14  UIKit                               0x0000000111b938bf -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	15  UIKit                               0x0000000111b8f893 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 109
	16  UIKit                               0x0000000111a1d7f3 _runAfterCACommitDeferredBlocks + 318
	17  UIKit                               0x0000000111a0a7bc _cleanUpAfterCAFlushAndRunDeferredBlocks + 532
	18  UIKit                               0x0000000111a3c28c _afterCACommitHandler + 137
	19  CoreFoundation                      0x0000000114a4e717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	20  CoreFoundation                      0x0000000114a4e687 __CFRunLoopDoObservers + 391
	21  CoreFoundation                      0x0000000114a33720 __CFRunLoopRun + 1200
	22  CoreFoundation                      0x0000000114a33016 CFRunLoopRunSpecific + 406
	23  GraphicsServices                    0x0000000116e2aa24 GSEventRunModal + 62
	24  UIKit                               0x0000000111a110d4 UIApplicationMain + 159
	25  Audiomesh                           0x000000010dede0c7 main + 55
	26  libdyld.dylib                       0x0000000115bbf65d start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by aure** [comment]
This is why it is so important to post code and not just error output.  Your microphone is connected to the output, through other things.  The problem is that you have locally defined nodes that are being lost when set up is complete.  Check out this video about connecting nodes:  https://vimeo.com/audiokit/connecting-nodes-part-2

**Comment by lususvir** [comment]
I'm not sure that's the issue. It was fully working before and after changing nothing, it now doesn't work. Plus, it's almost line for line based on the AudioKit recorder demo: http://audiokit.io/examples/RecorderDemo/

**Comment by aure** [comment]
Before the only reason it worked is because there was a memory leak - the nodes continued to exist without anything owning them.  That worked, but could lead to problems.  Now, the leak is fixed, but unowned nodes will disappear.  Can you try making those local mixers instance variables on your class?

**Comment by lususvir** [comment]
Yeah, I tried that and it still crashed. Here's the new code:

    var recorder: AKNodeRecorder?
    var mic: AKMicrophone?
    var micMixer: AKMixer?
    var mainMixer: AKMixer?
    var player: AKAudioPlayer?
    var micBooster: AKBooster?
    var moogLadder: AKMoogLadder?
    var delay: AKDelay?
    
View did load:

    do {
            try AKSettings.setSession(category: .playAndRecord, with: .defaultToSpeaker)
        } catch {
            print("Errored setting category.")
        }
        
        // Clean tempFiles !
        AKAudioFile.cleanTempDirectory()
        
        // Session settings
        AKSettings.bufferLength = .medium
        AKSettings.defaultToSpeaker = true
        
        // Patching
        mic = AKMicrophone()
        //        inputPlot.node = mic
        micMixer = AKMixer(mic)
        micBooster = AKBooster(micMixer)
        
        // Will set the level of microphone monitoring
        micBooster!.gain = 0
        recorder = try? AKNodeRecorder(node: micMixer)
        player = try? AKAudioPlayer(file: (recorder?.audioFile)!)
        player?.looping = false
        player?.completionHandler = playingEnded
        
        moogLadder = AKMoogLadder(player!)
        
        mainMixer = AKMixer(moogLadder!, micBooster!)
        
        AudioKit.output = mainMixer
        AudioKit.start()

**Comment by aure** [comment]
This code that you pasted in now works for me.

**Comment by LeeMatthewHiggins** [comment]
It seems my problem (the original ticket issue) was related to not holding onto the microphone object in my code. It must have worked before due to leaks. Strange that it works on the sim! I guess sim code must still have leaks, thats why it still worked. I wonder if the mic should be a singleton and be kept alive internally in audiokit?

**Comment by lususvir** [comment]
That's interesting, mine was crashing on the simulator.
